#!/usr/bin/env python3
"""Shared helpers for final artifact preflight validators."""

from __future__ import annotations

import json
import re
from collections import Counter
from pathlib import Path
from typing import Any


CHAPTER_FILE_RE = re.compile(r"^ch0*(\d+)_.*\.md$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
FOOTNOTE_DEFINITION_RE = re.compile(r"^\[\^([A-Za-z0-9_-]+)\]:")
FOOTNOTE_MARKER_RE = re.compile(r"\[\^([A-Za-z0-9_-]+)\]")
IMAGE_MARKDOWN_RE = re.compile(r"!\[[^\]]*\]\([^)]+\)")
IMAGE_HTML_RE = re.compile(r"<img\b", re.IGNORECASE)
URL_RE = re.compile(r"https?://[^\s)\]>\"']+")
TODO_RE = re.compile(r"\b(?:TODO|TBD)\b", re.IGNORECASE)

FINAL_BLOCKING_TEXT = (
    "[IMAGE:",
    "[이미지 생성 실패]",
    "[Image generation failed]",
    "Generated by Ebook Writer Agent",
    "{{",
    "}}",
    "{N}",
    "{번호}",
)


def issue(
    code: str,
    message: str,
    severity: str = "error",
    file: str | None = None,
    line: int | None = None,
    **extra: Any,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "severity": severity,
        "code": code,
        "message": message,
    }
    if file is not None:
        payload["file"] = file
    if line is not None:
        payload["line"] = line
    payload.update(extra)
    return payload


def result_payload(name: str, issues: list[dict[str, Any]], **summary: Any) -> dict[str, Any]:
    errors = [item for item in issues if item.get("severity") == "error"]
    warnings = [item for item in issues if item.get("severity") == "warning"]
    return {
        "validator": name,
        "status": "failed" if errors else "passed",
        "error_count": len(errors),
        "warning_count": len(warnings),
        "summary": summary,
        "issues": issues,
    }


def write_json(path: str | Path, payload: dict[str, Any]) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def load_json(path: str | Path) -> Any:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def chapter_number(path: str | Path) -> int | None:
    match = CHAPTER_FILE_RE.match(Path(path).name)
    if not match:
        return None
    return int(match.group(1))


def chapter_files(directory: str | Path) -> list[Path]:
    root = Path(directory)
    files = [path for path in root.glob("*.md") if chapter_number(path) is not None]
    return sorted(files, key=lambda path: (chapter_number(path) or 0, path.name))


def code_block_line_numbers(text: str) -> set[int]:
    lines = text.splitlines()
    in_fence = False
    code_lines: set[int] = set()
    for line_number, line in enumerate(lines, start=1):
        if line.strip().startswith("```"):
            code_lines.add(line_number)
            in_fence = not in_fence
            continue
        if in_fence:
            code_lines.add(line_number)
    return code_lines


def non_code_lines(text: str) -> list[tuple[int, str]]:
    code_lines = code_block_line_numbers(text)
    return [
        (line_number, line)
        for line_number, line in enumerate(text.splitlines(), start=1)
        if line_number not in code_lines
    ]


def headings(text: str) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    for line_number, line in non_code_lines(text):
        match = HEADING_RE.match(line)
        if not match:
            continue
        found.append(
            {
                "level": len(match.group(1)),
                "text": match.group(2).strip(),
                "line": line_number,
            }
        )
    return found


def code_fence_languages(text: str) -> list[str]:
    languages: list[str] = []
    in_fence = False
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped.startswith("```"):
            continue
        if not in_fence:
            languages.append(stripped[3:].strip())
        in_fence = not in_fence
    return languages


def image_reference_count(text: str) -> int:
    return len(IMAGE_MARKDOWN_RE.findall(text)) + len(IMAGE_HTML_RE.findall(text))


def urls(text: str) -> list[str]:
    return URL_RE.findall(text)


def footnote_info(text: str) -> dict[str, Any]:
    definitions: dict[str, list[int]] = {}
    markers: list[tuple[str, int]] = []

    for line_number, line in non_code_lines(text):
        definition_match = FOOTNOTE_DEFINITION_RE.match(line.strip())
        if definition_match:
            definitions.setdefault(definition_match.group(1), []).append(line_number)
            continue

        for marker_match in FOOTNOTE_MARKER_RE.finditer(line):
            markers.append((marker_match.group(1), line_number))

    return {
        "marker_ids": [marker_id for marker_id, _line in markers],
        "marker_counts": Counter(marker_id for marker_id, _line in markers),
        "marker_lines": markers,
        "definitions": definitions,
    }


def load_citation_ids(citations_path: str | Path | None) -> set[str] | None:
    if not citations_path:
        return None
    data = load_json(citations_path)
    citations = data if isinstance(data, list) else data.get("citations", [])
    citation_ids: set[str] = set()
    for citation in citations:
        if not isinstance(citation, dict):
            continue
        citation_id = citation.get("id")
        if isinstance(citation_id, (int, str)):
            citation_ids.add(str(citation_id))
    return citation_ids


def dangerous_text_issues(text: str, file_label: str, include_raw_footnotes: bool = False) -> list[dict[str, Any]]:
    issues: list[dict[str, Any]] = []
    for line_number, line in non_code_lines(text):
        for token in FINAL_BLOCKING_TEXT:
            if token in line:
                issues.append(
                    issue(
                        "forbidden_text",
                        f"Forbidden final-artifact text remains: {token}",
                        file=file_label,
                        line=line_number,
                        token=token,
                    )
                )
        if TODO_RE.search(line):
            issues.append(
                issue(
                    "todo_placeholder",
                    "TODO/TBD placeholder remains in reader-facing content",
                    file=file_label,
                    line=line_number,
                )
            )
        if include_raw_footnotes and FOOTNOTE_MARKER_RE.search(line):
            issues.append(
                issue(
                    "raw_footnote_marker",
                    "Raw footnote marker remains in final reader-facing content",
                    file=file_label,
                    line=line_number,
                )
            )
    return issues
